### ISSUE TITLE
Working configuration with systemjs, node and express statics routes

### ISSUE THREAD

**Issue by Fernando-ASX** [InfomediaLtd/angular2-materialize#288]
I'm trying to figure out how to do to materialize works with my current configurations.
As explained in issue #18 I already have a similar configuration in my index.ejs like this:
```
<!DOCTYPE html>
<html>
<head>
	<!-- Use the 'title' property to render a page title  -->
	<title><%= title %></title>
	<base href="/"/>

	<!-- Materialize css -->
	<link type="text/css" rel="stylesheet" href="lib/materialize-css/dist/css/materialize.css" media="screen,projection"/>

	<!-- Jquery and other scripts -->
	<script type="text/javascript" src="lib/jquery/dist/jquery.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.6/hammer.js"></script>
	<script type="text/javascript" src="lib/materialize-css/dist/js/materialize.js"></script>

</head>
<body>
	<my-app>
		<h1>Loading...</h1>
	</my-app>

	<script type="text/javascript">
		window.user = <%- user || null %>
	</script>

	<script src="lib/core-js/client/shim.min.js"></script>
	<script src="lib/zone.js/dist/zone.js"></script>
	<script src="lib/reflect-metadata/Reflect.js"></script>
	<script src="lib/systemjs/dist/system.js"></script>

	<script src="systemjs.config.js"></script>
	<script>
		System.import('app').catch(function(err){
			console.error(err);
		});
	</script>
</body>
</html>
```

And my systemjs config file is like this
```
(function(global){

    var packages = {
        app:{
            main:'./bootstrap.js',
            defaultExtension:'js'
        },
        'materialize-css':{
            main:'dist/js/materialize'
        },
        'materialize':{
            main:'dist/materialize-directive',
            defaultExtension:'js'
        },
        'traceur':{
            main:'bin/traceur',
            defaultExtension:'js'
        }
    };

    var map = {
        '@angular':'lib/@angular',
        'rxjs':'lib/rxjs',
        'materialize-css':'lib/materialize-css',
        'materialize':'lib/angular2-materialize',
        'angular2-materialize':'lib/angular2-materialize',
        'traceur':'lib/traceur'
    };

    var ngPackageNames = [
        'common',
        'compiler',
        'core',
        'forms',
        'http',
        'router',
        'platform-browser',
        'platform-browser-dynamic'
    ];

    ngPackageNames.forEach(function(pkgName){
        packages['@angular/' + pkgName] = {
            main:'/bundles/' + pkgName + '.umd.js',
            defaultExtension:'js'
        };
    });

    System.config({
        defaultJSExtensions:true,
        transpiler:null,
        packages:packages,
        map:map
    });

})(this);
```

Currently i have express static route "/lib" pointing to "node_modules" folder.

I am facing problems with traceur to compile materialize_directive, with the following error:

Error: (SystemJS) Unexpected value 'undefined' imported by the module 'AppModule'
	Error: Unexpected value 'undefined' imported by the module 'AppModule'
	    at eval (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:14083:33)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:14063:46)
	    at RuntimeCompiler._compileComponents (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:16809:49)
	    at RuntimeCompiler._compileModuleAndComponents (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:16747:39)
	    at RuntimeCompiler.compileModuleAsync (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:16738:23)
	    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3000/lib/@angular/core//bundles/core.umd.js:6565:29)
	    at PlatformRef_.bootstrapModule (http://localhost:3000/lib/@angular/core//bundles/core.umd.js:6547:25)
	    at execute (http://localhost:3000/app/bootstrap.js:14:65)
	Error loading http://localhost:3000/app/bootstrap.js
	    at eval (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:14083:33)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:14063:46)
	    at RuntimeCompiler._compileComponents (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:16809:49)
	    at RuntimeCompiler._compileModuleAndComponents (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:16747:39)
	    at RuntimeCompiler.compileModuleAsync (http://localhost:3000/lib/@angular/compiler//bundles/compiler.umd.js:16738:23)
	    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3000/lib/@angular/core//bundles/core.umd.js:6565:29)
	    at PlatformRef_.bootstrapModule (http://localhost:3000/lib/@angular/core//bundles/core.umd.js:6547:25)
	    at execute (http://localhost:3000/app/bootstrap.js:14:65)
	Error loading http://localhost:3000/app/bootstrap.js

And if i delete the traceur map in systemjs config, i got:

Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/traceur.js
	Error loading http://localhost:3000/traceur.js
	Unable to load transpiler to transpile http://localhost:3000/lib/angular2-materialize/dist/materialize-directive.js
	Error loading http://localhost:3000/lib/angular2-materialize/dist/materialize-directive.js as "angular2-materialize" from http://localhost:3000/app/app.module.js
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/traceur.js
	Error loading http://localhost:3000/traceur.js
	Unable to load transpiler to transpile http://localhost:3000/lib/angular2-materialize/dist/materialize-directive.js
	Error loading http://localhost:3000/lib/angular2-materialize/dist/materialize-directive.js as "angular2-materialize" from http://localhost:3000/app/app.module.js

Any kind of help will be appreciated.
(NOTE: please considere the fact that english is not my mother tongue, so please be patient)
Thank you in advance.

**Comment by Sb8691** [comment]
Hi, The same Error here
