### ISSUE TITLE
Error with Angular Universal build after importing MaterializeModule.

### ISSUE THREAD

**Issue by biskazz** [InfomediaLtd/angular2-materialize#371]
What I have is [this official Angular Universal demo](https://github.com/angular/universal-starter/tree/master/cli). The problem is when I add MaterializeModule to app.module.ts I get the following error.

```
C:\Development\Tests\node_modules\angular2-materialize\dist\materialize-module.js:1
(function (exports, require, module, __filename, __dirname) { import { NgModule } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.JbiC (C:\Development\Tests\dist\dist-server\main.bundle.js:1:7570)

```

I posted on #140 but I was told that the issue there is not related to mine. I tried adding `"allowJs":true` as @bisubus suggested there but no success with that.

**Comment by bisubus** [comment]
@biskazz The issue is specific to your particular build. I'd suggest to post a question at Stackoverflow with provided way to replicate the problem.

**Comment by biskazz** [comment]
I already did that and no response for 3ish days now. On the Angular Universal GitHub page there are a lot of similar issues. [What can be done? ](https://github.com/angular/angular-cli/issues/7200#issuecomment-329711848)
Asking here because I feel we have the highest change of finding a workaround for this particular problem if fixing it is not possible.

**Comment by enzolry** [comment]
Same problem here, it seems that this version is not universal-compatible because of the way it is bundled. Haven't found a solution for now :/
