### ISSUE TITLE
Unable to build locally using build.sh

### ISSUE THREAD

**Issue by wkamir** [InfomediaLtd/angular2-materialize#378]
Steps to reproduce:

```
git clone https://github.com/InfomediaLtd/angular2-materialize.git
npm install
bash ./build.sh
```

I get the following error:

```
/development/Angular/npm/angular2-materialize/node_modules/.bin/ngc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
./build.sh: line 17: rsync: command not found
root@40668c38786c:/development/Angular/npm/angular2-materialize#
```

What could I be missing?

I tried it on my Windows 10 machine and also on a Linux box.

**Comment by rubyboy** [comment]
What Linux distro are you using?
The fact that it can't find "rsync" is weird. I thought that every common distro would have rsync on it...

Also, try running "node node_modules/.bin/ngc -p src/tsconfig.json" and see if that works. this is the command that it's running inside build.sh

**Comment by jpremkumar** [comment]
I'm also facing the same issue. Tried @rubyboy suggestion. Still getting the same issue. 

Any other solution, please.

**Comment by jpremkumar** [comment]
I am facing the same issue. Tried @rubyboy suggestion, still getting same issue. I tried with comment out _rsync_ but no luck.

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Any other solution, please.

**Comment by AlbertJvR** [comment]
Hey man. Run "ng build", copy the package.json from the src directory into the folder within the dist folder, then run "npm pack ./dist/product-view"......
Replace "product-view" with whatever is the name of the directory in the dist folder
